apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-memcached-exporter.fullname" . }}
  labels:
{{ include "prometheus-memcached-exporter.labels" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: memcached-exporter
      port: {{ .Values.service.port }}
      targetPort: exporter-port
      protocol: TCP
  selector:
    app: {{ template "prometheus-memcached-exporter.name" . }}
    release: {{ .Release.Name }}
