{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-memcached-exporter.serviceAccountName" . }}
  labels:
{{ include "prometheus-memcached-exporter.labels" . | indent 4 }}
{{- end -}}
