apiVersion: v2
appVersion: 1.27.0
description: Prometheus exporter for Redis metrics
name: nc-prometheus-redis-exporter
version: 4.6.0
home: https://github.com/oliver006/redis_exporter
sources:
  - https://github.com/oliver006/redis_exporter
keywords:
  - prometheus
  - redis
maintainers:
  - name: acondrat
    email: arcadie.condrat@gmail.com
  - name: zanhsieh
    email: zanhsieh@gmail.com
type: application
