---
# Choose endpoint type (this will override the value of clouds.yaml)
endpoint_type: public
cloud: openstack

image:
  repository: quay.io/niedbalski/openstack-exporter-linux-amd64
  tag: v1.2.0
  pullPolicy: Always

# For PrometheusRule
serviceMonitor:
  interval: 1m
  scrapeTimeout: 30s

# Add extra args to the exporter.
# Doc: https://github.com/openstack-exporter/openstack-exporter#command-line-options
extraArgs:
#  - --disable-service.baremetal
#  - --disable-service.container-infra
#  - --disable-service.object-store

# Add extra labels
#commonLabels:
#  prometheus.io/monitor: "true"

# Generate a secret for clouds.yaml
# Doc: https://github.com/openstack-exporter/openstack-exporter#openstack-configuration
clouds_yaml_config: |
  clouds.yaml: |
      clouds:
        openstack:
          auth:
            auth_url: http://192.168.5.31/identity
            username: "admin"
            password: "secret"
            project_id: 59f3b0c57bb34091bc35658320f447ae
            user_domain_name: "Default"
          region_name: "RegionOne"
          interface: "public"
          identity_api_version: 3